# Welcome to Jekyll!
#
# !!! DONT FORGET TO -C AND RESTART JEKYLL AFTER MODIFYING THIS FILE !!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tyler Van Schaick
author: Site admin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  front-end web dev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/New_York

# specify markdown to use
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

# custom site variables
# repo_url: https://github.com/tyler-vs/tyler-vs.github.io
# url: https://tyler-vs.github.io/
# version: 1.0.0

# author_info:
#   first_name: 'tyler'
#   last_name: 'van schaick'
#   email: ''

# codepen_api_settings:
#   pen-height: 265
#   pen-theme-id: 0
  # add back up pen hash ???
  # pen-slug-hash="ZQBMVq"
  # pen-default-tab: result
  # pen-user: tvs
  # pen-embed-version: 2
  # pen-pen-title="Halo 3 Hex Color Codes"
  # pen-preview="true"

social_media_accounts:
  # twitter_username: ''
  linkedin_username: 'https://www.linkedin.com/in/tylervs/'
  # facebook_username: ''
  # codepen_username: tvs
  github_username: 'https://github.com/tyler-vs'
  stackoverflow_username: 'https://stackoverflow.com/users/7221168/tyler-vs'

# post excerpt separator, will limit what content appears
# when displaying a post loop.
# excerpt_separator: <!--more-->

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock

# specify sass directory
sass:
  sass_dir: _sass
  # different output styles can be found here:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: compressed

# build settings
markdown: kramdown

# portfolio collection
collections:
  projects:
    output: true

defaults:
  -
    scope:
      # path: 'projects'
      type: 'projects'
    values:
      layout: 'page'